
spring:
  application:
    name: ferrari-auth
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0


server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log4j2.xml
